---
title: "Campbell640Week11-12"
output: pdf_document
date: "2023-11-06"
always_allow_html: true
---

```{r setup, include=FALSE}
setwd("C:/Users/jcamp/Documents/DSC640/Assignments/data sources")

# Load libraries
library(ggplot2)
library(dplyr)
library(plotly)

# Load file
education <- read.csv("ex6-2/education.csv")
unemployment <- read.csv("unemployement-rate-1948-2010.csv")

# Kaggle: https://www.kaggle.com/datasets/benroshan/ecommerce-data?select=Sales+target.csv
orders <- read.csv("Order Details.csv")
target <- read.csv("Sales target.csv")
list <- read.csv("List of Orders.csv")
```

## R - Histogram
```{r echo=FALSE}
ggplot(education, aes(x=percent_graduates_sat)) + geom_histogram(bins=5, col="grey")+
  ggtitle("Histogram - Percent Graduated") +
  xlab("Percent Graduated") + 
  ylab("Frequency")
```

## R - Box Plot
```{r echo=FALSE}
# Summarize number of winners by country
rates_df = unemployment %>%
  mutate(decade = floor(Year/10)*10) %>% 
  group_by(decade) %>%
  filter(decade >= 1960 & decade  < 2010)

ggplot(data=rates_df, mapping=aes(x=decade, y=Value, group=decade))+geom_boxplot()+
  ggtitle("Unemployment Rates by Decade") +
  xlab("Decade") + 
  ylab("Unemployment Rate %")
```

## R - Bullet Chart
```{r echo=FALSE}
target$Month.of.Order.Date = as.Date(paste("01-", target$Month.of.Order.Date, sep = ""), format = "%d-%b-%y")

target <- target %>%
            filter(Month.of.Order.Date >= '2018-01-01' & Month.of.Order.Date  <= '2018-12-01') %>%
            group_by(Category) %>%
            summarise(Target = sum(Target)) 
```

```{r echo=FALSE}
list$Order.Date = as.Date(list$Order.Date, format = "%d-%m-%Y")

list <- list %>%
  filter(Order.Date>= '2018-01-01' & Order.Date <= '2018-12-31')


orders <- orders %>%
            filter(orders$Order.ID %in% list$Order.ID) %>%
            group_by(Category) %>%
            summarise(Amount = sum(Amount)) 
```


```{r message=FALSE, warning=FALSE, echo=FALSE}
fig <- plot_ly()

  fig <- fig %>%
    add_trace(
    type = "indicator",
    mode = "gauge",
    domain = list(x = c(0.25, 1), y = c(0.08, 0.25)),
    title = list(text = orders$Category[3]),
    gauge = list(
      shape = "bullet",
      axis = list(range = list(NULL, 140000)),
      threshold = list(
        line = list(color = "red", width = 2),
        thickness = 0.75,
        value = target$Target[3]),
      steps = list(
      list(range = c(0, orders$Amount[3]), color = "lightgray"))),
  height = 150, width = 600) 

  fig <- fig %>%
    add_trace(
    type = "indicator",
    mode = "gauge",
    domain = list(x = c(0.25, 1), y = c(0.4, 0.6)),
    title = list(text = orders$Category[2]),
    gauge = list(
      shape = "bullet",
      axis = list(range = list(NULL, 140000)),
      threshold = list(
        line = list(color = "red", width = 2),
        thickness = 0.75,
        value = target$Target[2]),
      steps = list(
      list(range = c(0, orders$Amount[2]), color = "lightgray"))),
  height = 150, width = 600) 
  
  fig <- fig %>%
    add_trace(
    type = "indicator",
    mode = "gauge",
    domain = list(x = c(0.25, 1), y = c(0.7, 0.9)),
    title = list(text = orders$Category[1]),
    gauge = list(
      shape = "bullet",
      axis = list(range = list(NULL, 140000)),
      threshold = list(
        line = list(color = "red", width = 2),
        thickness = 0.75,
        value = target$Target[1]),
      steps = list(
      list(range = c(0, orders$Amount[1]), color = "lightgray"))),
  height = 150, width = 600) 


fig
```
## Code Repository
```{r ref.label = knitr::all_labels(), echo = TRUE, eval = FALSE}
```